apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dwk-project-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PacoZG/dwk-project-prod
    targetRevision: main
    path: deploy/kubernetes/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
