apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prod-project-manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer # Recommended for local volumes to ensure node affinity is respected
reclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-project-pv
spec:
  storageClassName: prod-project-manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube/project
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-project-files-claim
spec:
  storageClassName: prod-project-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
