apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
spec:
  selector:
    matchLabels:
      app: server
  template:
    spec:
      containers:
        - name: server
          env:
            - name: POSTGRES_HOST
              value: prod-postgres-svc
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: prod-project-files-claim
